
default_platform(:ios)

platform :ios do


lane :test do
    if !Dir.entries('.').select { |f| f =~ /.*\.xcworkspace/ }.empty?
      scan(
        workspace: Dir.entries('.').select { |f| f =~ /.*\.xcworkspace/ }[0],
        code_coverage: true,
      )
      slather(cobertura_xml: true,
        workspace: Dir.entries('.').select { |f| f =~ /.*\.xcworkspace/ }[0]
      )
    else
      scan(
        project: Dir.entries('.').select { |f| f =~ /.*\.xcodeproj/ }[0],
        code_coverage: true,
      )
      slather(cobertura_xml: true,
        proj: Dir.entries('.').select { |f| f =~ /.*\.xcodeproj/ }[0]
      )
    end
  end


end

end
